project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://siyabongamat.github.io # you must change this appropriately for RSS feeds to work properly
  title: "siyabongamat.github.io"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/SiyabongaMat
    left: 
      - text: "Classify Animals"
        href: classify.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



